"""
Theme Model
AI-generated clusters of related feedback
"""

from sqlalchemy import Column, String, Text, Integer, ForeignKey, Float, JSON
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import relationship

from app.models.base import TenantScopedModel


class Theme(TenantScopedModel):
    """
    Theme/Cluster of related feedback items
    Auto-generated by AI clustering
    """

    __tablename__ = "theme"

    # Tenant association
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False, index=True)

    # Product association (nullable for backward compatibility)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True, index=True)

    # Basic Information
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)  # AI-generated summary

    # Categorization
    primary_category = Column(String(50), nullable=True)  # Most common category in cluster

    # Metrics
    feedback_count = Column(Integer, default=0)  # Number of feedback items in this theme
    account_count = Column(Integer, default=0)  # Number of unique accounts
    total_arr = Column(Float, default=0.0)  # Total ARR of affected accounts

    # Scoring
    urgency_score = Column(Float, nullable=True)  # 0 to 1 - How urgent is this?
    impact_score = Column(Float, nullable=True)  # 0 to 1 - How impactful is this?
    confidence_score = Column(Float, nullable=True)  # 0 to 1 - How confident is the clustering?

    # Trend Analysis
    trend = Column(String(20), nullable=True)  # increasing, stable, decreasing
    trend_percentage = Column(Float, nullable=True)  # % change over time

    # Segmentation
    affected_segments = Column(ARRAY(String), nullable=True)  # Which segments care about this

    # AI Analysis
    key_quotes = Column(JSON, nullable=True)  # Representative quotes
    # Example: [{"text": "quote", "feedback_id": 123, "account_name": "Acme Corp"}]

    suggested_solutions = Column(JSON, nullable=True)  # AI-suggested approaches

    # Metadata
    extra_data = Column(JSON, nullable=True)

    # Relationships
    tenant = relationship("Tenant", back_populates="themes")
    product = relationship("Product", back_populates="themes")
    feedback_items = relationship("Feedback", back_populates="theme")
    context_sources = relationship("ContextSource", back_populates="theme")
    initiatives = relationship("Initiative", secondary="theme_initiative", back_populates="themes")

    def __repr__(self):
        return f"<Theme(id={self.id}, title='{self.title}', feedback_count={self.feedback_count}, arr={self.total_arr})>"
